### ISSUE TITLE
Add Whtie and Black to blinkscript

### ISSUE THREAD

**Issue by EmberLightVFX** [calvinsilly/Tetrahedral-Interpolation#1]
Would love to get the white and black sliders from TetraInterp_Expression_02.nk into the blink script.
A lot of Fusion users have requested this feature but I'm not as good in math as you are so no idea how to transfer the expression code to the blinkscript code (so I can turn that into Fuse code)

Cheers!

**Comment by calvinsilly** [comment]
Ah sure thing!
