### ISSUE TITLE
Problem with TetraAutomater

### ISSUE THREAD

**Issue by luckymikimochi** [calvinsilly/Tetrahedral-Interpolation#2]
Hi ! 
First of all, thanks a lot for this project! It's awesome the work you did :)

according, to the demo, i've been trying the TetraAutomater to match two footages, booth with a color chart in it

it seems to work fine with all colors except yellow. When i enter values in the yellow input tabs and then hit "calculate", i get an error message from nuke saying "expecting a float, Add found".

Do you have any clues about where the problem comes from?

Thanks a lot!

**Comment by calvinsilly** [comment]
What version of SymPy are you using?

I know that version 1.6.2 and below should work. Version 1.7 and up changed a few things with how the solver works.

**Comment by luckymikimochi** [comment]
I just realized that i had an newer version of SymPy (1.8), but i got the 1.5 version and it's working fine now !

Thanks for the quick reply! and again, big shoutout to this!

Hope this will help other people for the futur :)
